### ISSUE TITLE
reminder: implement extends array resolve if it lands

### ISSUE THREAD

**Issue by dominikg** [dominikg/tsconfck#67]
see https://github.com/microsoft/TypeScript/pull/50403 and https://github.com/microsoft/TypeScript/issues/29118

**Comment by dominikg** [comment]
under consideration for ts 5.0 https://github.com/microsoft/TypeScript/issues/51362

**Comment by 7rulnik** [comment]
@dominikg it's already available in 5.0 beta
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends

**Comment by dominikg** [comment]
thanks for the ping! can't get ti it before next week.

contributions welcome ;)

**Comment by dominikg** [comment]
released tsconfck@2.1.0-next.0 with support for extends array and moduleResolution: bundler

**Comment by alexlafroscia** [comment]
@dominikg thanks for getting a release with this update published!

I came across this need trying to use Vite with a TypeScript 5 project and an `extends` array, which resulted in an exception within Vite that I eventually tracked back to this package.

This package is bundled into the published Vite package, meaning I can't use a resolution or something to upgrade the version that my app ends up using. This means Vite will need to update to use a new release of `tsconfck` on their end and publish a release with it in order to fix that incompatibility.

All that to ask... do you have any thoughts on when a `2.1.0` _non_ pre-release might be ready, so I can update Vite to make use of that? I'm not sure they would want a PR upgrading to a pre-release version, but it would be really great to try to get Vite's compatibility with TypeScript 5 straightened out before the official TypeScript 5 release, where I'm sure there will be a flood of folks looking for those things to work together.

**Comment by dominikg** [comment]
not until typescript 5.0 final is released i'm afraid. typescript uses a versioning scheme for their beta/rc releases that makes it hard to add to peer dependencies  ( 5.0.0-beta, 5.0.1-rc, i assume final release will be 5.0.2 or 5.0.3). 

It is likely that vite can add support for typescript 5 in a minor release, 4.2-beta is currently under way, but is likely to be released before ts5 final. So currently my best guess is that vite 4.3 is going to add support for new ts5 features. 

You should still be able to use ts5 in place of ts4 as long as you stay within ts4 syntax

**Comment by alexlafroscia** [comment]
Thanks for such a detailed response! It's really helpful to know how that timeline works, I really appreciate it 🙌

**Comment by dominikg** [comment]
released tsconfck 2.1.0 and sent a PR to vite to update to it https://github.com/vitejs/vite/pull/12401

That PR may land in vite 4.2 if the final release of typescript 5.0 happens tomorrow and vite 4.2 is released after that, but no promises.

**Comment by dominikg** [comment]
I had the timelines for vite 4.2 and typescript 5 a bit wrong in my comment above, looks like ts5 is going to be out before vite 4.2 so it can be added.

vite@4.2.0-beta.2 contains tsconfck 2.1.0, please test @alexlafroscia
